<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-MotivPlanBackend.Worker-c5a76fbd-c317-481e-a8f5-b27ca90d7fbd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MotivPlanBackend.Contracts\MotivPlanBackend.Contracts.csproj" />
  </ItemGroup>
</Project>
