// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotivPlanBackend.Persistence.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotivPlanBackend.Persistence.Migrations
{
    [DbContext(typeof(MotivPlanDbContext))]
    partial class MotivPlanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.ExerciseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("System");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercises", "public");
                });

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.UserWorkoutEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("System");

                    b.Property<DateOnly>("Schedule")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutStatus");

                    b.ToTable("UserWorkout", "public");
                });

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.WorkoutEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("System");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Workouts", "public");
                });

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.WorkoutExerciseEntity", b =>
                {
                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsTime")
                        .HasColumnType("boolean");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.HasKey("WorkoutId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WorkoutExercises", "public");
                });

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.WorkoutStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("upper(\"Name\")", true);

                    b.HasKey("Id");

                    b.ToTable("WorkoutStatus", "public");
                });

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.UserWorkoutEntity", b =>
                {
                    b.HasOne("MotivPlanBackend.Domain.Entities.WorkoutEntity", "Workout")
                        .WithMany("UsersWorkouts")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotivPlanBackend.Domain.Entities.WorkoutStatusEntity", "WorkoutStatusEntity")
                        .WithMany("UsersWorkouts")
                        .HasForeignKey("WorkoutStatus")
                        .IsRequired();

                    b.Navigation("Workout");

                    b.Navigation("WorkoutStatusEntity");
                });

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.WorkoutExerciseEntity", b =>
                {
                    b.HasOne("MotivPlanBackend.Domain.Entities.ExerciseEntity", "Exercise")
                        .WithMany("WorkoutsExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotivPlanBackend.Domain.Entities.WorkoutEntity", "Workout")
                        .WithMany("WorkoutsExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.ExerciseEntity", b =>
                {
                    b.Navigation("WorkoutsExercises");
                });

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.WorkoutEntity", b =>
                {
                    b.Navigation("UsersWorkouts");

                    b.Navigation("WorkoutsExercises");
                });

            modelBuilder.Entity("MotivPlanBackend.Domain.Entities.WorkoutStatusEntity", b =>
                {
                    b.Navigation("UsersWorkouts");
                });
#pragma warning restore 612, 618
        }
    }
}
